### PR TITLE
Fix L8 cached routes

### PR DESCRIPTION
**Pull request by bumbummen99**
This will fix the following error when using cached routes without the $namespace member in your RouteServiceProvider:

```
Argument 1 passed to CodeZero\LocalizedRoutes\UrlGenerator::__construct() must be an instance of Illuminate\Routing\RouteCollection, instance of Illuminate\Routing\CompiledRouteCollection given, called in /var/www/vendor/codezero/laravel-localized-routes/src/LocalizedRoutesServiceProvider.php on line 104
```
This is caused by using `php artisan route:cache` as the provided type will be [CompiledRouteCollection](https://laravel.com/api/7.x/Illuminate/Routing/CompiledRouteCollection.html)

### CODE REVIEW

**Comment by bumbummen99** [comment]
Had to remove Laravel < 7 support as the [RouteCollection](https://laravel.com/api/6.x/Illuminate/Routing/RouteCollection.html) does not implement the [RouteCollectionInterface](https://laravel.com/api/7.x/Illuminate/Routing/RouteCollectionInterface.html)

**Comment by ivanvermeyen** [comment]
Hi, thanks for catching that.

I think there are 2 options.

First one seems to fix the problem while keeping compatibility with older Laravel versions, but it might be not best practice: removing the typehint in the constructor and let the parent class handle that... I don't know if that is acceptable?

Secondly we can apply your fix, which is clearly nicer in code, but removes compatibility with older versions.
I then also need to figure out how to change the 2.3.0 release to 3.0.0 since it is a breaking change... Can I just update that without messing up people's projects? Or do I need to revert Laravel 8 related commits, then tag a new minor version and then reapply the Laravel 8 commits?

**Comment by bumbummen99** [comment]
> Hi, thanks for catching that.
> 
> I think there are 2 options.
> 
> First one seems to fix the problem while keeping compatibility with older Laravel versions, but it might be not best practice: removing the typehint in the constructor and let the parent class handle that... I don't know if that is acceptable?
> 
> Secondly we can apply your fix, which is clearly nicer in code, but removes compatibility with older versions.
> I then also need to figure out how to change the 2.3.0 release to 3.0.0 since it is a breaking change... Can I just update that without messing up people's projects? Or do I need to revert Laravel 8 related commits, then tag a new minor version and then reapply the Laravel 8 commits?

It may be better or cleaner code wise but if the aim of the package is to also provide newer features and updates to those versions then i think your suggestion is perfectly fine :+1:, tought i just added some manual checking to be on the safe side.
If an invalid type is provided it will throw an InvalidArgumentException. With this there should not be the need for an major/minor version as it will stay compatible :smiley:

**Comment by ivanvermeyen** [comment]
You're awesome! Thanks!
I'll tag a new release and make a note to add a test for the route caching 👍

**Pull request merged**
